[build-system]
requires = ["setuptools>=83.0.0", "setuptools-scm>=10.2.0"]
build-backend = "setuptools.build_meta"

[project]
name = "opticalglass"
description = "Tools for reading optical material catalogs and libraries"
readme = "docs/README.rst"

license = "BSD-3-Clause"
license-files = ["LICENSE",]

authors = [
    {name = "Michael J Hayford", email = "mjhoptics@gmail.com"},
]

classifiers = [ 
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Physics",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Development Status :: 5 - Production/Stable",
]
keywords = [ "glass", "optical glass", "refractive index", "optics", 
             "glass catalog",]

requires-python = ">=3.12"

dependencies = [ 
    "numpy>=2.5.1", 
    "scipy>=1.18.0", 
    "matplotlib>=3.11.0", 
    "pandas>=3.0.3", 
    "xlrd>=2.0.2", 
    "openpyxl>=3.1.5", 
    "zemaxglass@git+https://github.com/mjhoptics/zemaxglass.git@3ef1cd8974709b3860ac581c5110ef289cbffbf5",
    "requests>=2.34.2", 
    "json_tricks>=3.17.3", 
    "pyyaml>=6.0.3", 
    "pyside6>=6.11.1",
]
dynamic = [ "version",]

[project.urls]
Homepage = "https://github.com/mjhoptics/opticalglass"
Changelog = "https://opticalglass.readthedocs.io/en/stable/changelog.html"
Documentation = "https://opticalglass.readthedocs.io/en/stable/"
"Bug Tracker" = "https://github.com/mjhoptics/opticalglass/issues"
"Source Code" = "https://github.com/mjhoptics/opticalglass"

[project.optional-dependencies]
testing = [ "setuptools", "pytest", "pytest-cov",]
rtd = [ "sphinx", "sphinx_rtd_theme",]
dev = [ "opticalglass[testing, rtd]",]

[project.gui-scripts]
glassmap = "opticalglass.glassmapviewer:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.package-data]
data = [ "*.xlsx", "*.xls", "*.txt",]

[tool.setuptools_scm]

[tool.pytest.ini_options]
addopts = "--verbose"
norecursedirs = [ "dist", "build", ".tox",]
testpaths = [ "tests",]
